# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveLostNoitce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item_lost', models.CharField(max_length=200)),
                ('detail_item_lost', models.CharField(max_length=1000)),
                ('time_submit_item_lost', models.DateTimeField(verbose_name='date published')),
                ('owner_item_lost', models.CharField(max_length=200)),
                ('email_owner_item_lost', models.CharField(max_length=200)),
                ('telephone_number_owner_item_lost', models.CharField(max_length=200)),
            ],
        ),
    ]
