# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostNoitceApp', '0004_auto_20170426_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='findownerlist',
            name='title_notice',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostnoticelist',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
