# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FindOwnerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name_item', models.CharField(max_length=200)),
                ('time_found', models.CharField(max_length=200)),
                ('location_found', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=1000)),
                ('your_name', models.CharField(max_length=200)),
                ('your_email', models.CharField(max_length=200)),
                ('found_owner', models.BooleanField(default=False)),
                ('time_submit', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='LostNoticeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name_item', models.CharField(max_length=200)),
                ('time_lost', models.CharField(max_length=200)),
                ('location_lost', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=1000)),
                ('your_name', models.CharField(max_length=200)),
                ('your_email', models.CharField(max_length=200)),
                ('found_it', models.BooleanField(default=False)),
                ('time_submit', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('time_register', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
