# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostnotice', '0002_auto_20170710_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findownerlist',
            name='time_submit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
